"""
Jira Task Extractor Agent

Analyzes assigned Jira tickets to extract important tickets and save them to DB.
"""

import logging
import os
from typing import Any, Dict, List, Optional
from app.cc_agents.memory_retriever.agent import call_memory_retriever
from app.cc_tools.jira_tasks import create_jira_tasks_mcp_server
from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)


def create_system_prompt(state_prompt: str, bot_name: str) -> str:
    """Create system prompt for Jira task extractor

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()
        bot_name: Bot name

    Returns:
        str: System prompt including agent behavior and tool usage principles
    """
    system_prompt = f"""You are {bot_name}, a virtual coworker who communicates via Slack.

# Basic Instructions
Analyze the received Jira tickets to extract **tasks you need to do** and save them to DB.

{state_prompt}

## Core Action Principles
<important_actions>
1. Analyze the received Jira tickets to extract tasks you need to do.
2. If necessary, use Rovo MCP tools to query ticket details.
3. If there are tasks to do, save them to DB using `mcp__jira_tasks__add_jira_task`.
4. Summarize and output the processing results.
</important_actions>

## Tool Usage Principles
<how_to_use_tool>
1. If tasks cannot be identified from ticket info alone, you must query details using Rovo MCP tools.
2. The reporter's user_id, user_name, channel_id must be found from retrieved_memory.
   - There is a reporter email in the ticket, so search memory with that email.
3. The `text` parameter of `mcp__jira_tasks__add_jira_task` must follow this format:
   "{bot_name}, a [task name] task has been assigned via [ticket key] ticket. Please complete the task and mark [ticket key] ticket as Done."
   Example: "{bot_name}, a code review task has been assigned via PROJ-123 ticket. Please complete the task and mark PROJ-123 ticket as Done."
4. If there are multiple tasks in one ticket, each must be saved **separately**.
5. If user_id, user_name, channel_id cannot all be found, do not save that task.
6. All assigned tickets are tasks you must handle, so extract the tasks from each ticket.
7. If you need to create files, always create them temporarily in `FILESYSTEM_BASE_DIR/checkers/tmp/` directory, and delete after completion.
</how_to_use_tool>

## Guardrail Policy
<guardrails>
**File System Access Restriction:**
- Never access files or directories outside FILESYSTEM_BASE_DIR
- Reading or modifying system files, home directory, config files, etc. is strictly prohibited
- File operations must be limited to within FILESYSTEM_BASE_DIR
</guardrails>"""

    return system_prompt


async def call_jira_task_extractor(issues: List[Dict[str, Any]]) -> Optional[str]:
    """
    Analyzes batch of Jira tickets to extract tasks and save them to DB.

    Args:
        issues: Issue list (including key, fields)

    Returns:
        Optional[str]: Processing result summary (None if no tasks)
    """
    if not issues:
        return None

    # Get settings and bot_name first
    from app.cc_agents.state_prompt import create_state_prompt
    from app.config.settings import get_settings

    settings = get_settings()
    bot_name = settings.BOT_NAME or "Bot"

    # Convert issue list to text
    issues_text = ""
    for idx, issue in enumerate(issues, 1):
        issue_key = issue.get("key", "")
        fields = issue.get("fields", {})

        summary = fields.get("summary", "")
        status = fields.get("status", {}).get("name", "Unknown")
        priority = fields.get("priority", {}).get("name", "Medium")
        issue_type = fields.get("issuetype", {}).get("name", "Task")
        updated = fields.get("updated", "")
        created = fields.get("created", "")

        # Generate issue URL
        issue_url = f"{settings.ATLASSIAN_JIRA_SITE_URL}/browse/{issue_key}"

        # Include brief description
        description = fields.get("description", "")
        description_preview = (
            description[:200] + "..."
            if description and len(description) > 200
            else description
        )

        # Assignee info
        assignee = fields.get("assignee", {})
        assignee_name = assignee.get("displayName", "None") if assignee else "None"
        assignee_email = assignee.get("emailAddress", "") if assignee else ""

        # Reporter info
        reporter = fields.get("reporter", {})
        reporter_name = reporter.get("displayName", "None") if reporter else "None"
        reporter_email = reporter.get("emailAddress", "") if reporter else ""

        issues_text += f"""
Ticket {idx}:
Issue Key: {issue_key}
Title: {summary}
URL: {issue_url}
Status: {status}
Priority: {priority}
Type: {issue_type}
Assignee: {assignee_name} <{assignee_email}>
Reporter: {reporter_name} <{reporter_email}>
Created: {created}
Updated: {updated}
Description Preview: {description_preview}

---
"""

    jira_task_memory_query = f"""Find information about all people related to the following {len(issues)} Jira tickets and compile memory.
Make sure to include **instructions** and information (channel_id, user_id, user_name) about the channel and requesting user.

{issues_text}"""

    # 1. Memory search (for jira task extractor)
    retrieved_memory = await call_memory_retriever(jira_task_memory_query)
    logging.info(
        f"[JIRA_TASK_EXTRACTOR] Memory retrieved: {retrieved_memory[:100] if retrieved_memory else 'None'}..."
    )

    state_prompt = create_state_prompt()

    # Add memory
    state_prompt += f"\n\n## Related Memory\n<retrieved_memory>\n{retrieved_memory}\n</retrieved_memory>"

    system_prompt = create_system_prompt(state_prompt, bot_name)

    # 2. Call jira task extractor
    query = f"""Extract tasks you need to do from the following {len(issues)} Jira tickets and save them to DB.

{issues_text}

Analyze each ticket and extract specific tasks (code review, test writing, deployment, etc.)."""

    # Atlassian MCP server settings (remote)
    mcp_servers = {
        "atlassian": {
            "command": "npx",
            "args": ["mcp-cache", "npx", "-y", "mcp-remote", "https://mcp.atlassian.com/v1/sse"],
        },
        "jira_tasks": create_jira_tasks_mcp_server(),
    }

    options = ClaudeAgentOptions(
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_SIMPLE,
        permission_mode="bypassPermissions",
        allowed_tools=["*"],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
            "Write",
            "Edit",
            "NotebookEdit",
        ],
        setting_sources=["project"],
        cwd=os.getcwd(),
        mcp_servers=mcp_servers,
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(query)

            result_message = ""
            async for message in client.receive_response():
                if isinstance(message, ResultMessage):
                    result_message = message.result.strip()
                    logging.info(
                        f"[JIRA_TASK_EXTRACTOR] Result: {result_message[:100]}..."
                    )
                    break

            # Return None if no tasks
            if not result_message or (
                "no task" in result_message.lower() and "found" in result_message.lower()
            ):
                logging.info("[JIRA_TASK_EXTRACTOR] No tasks extracted")
                return None

            return result_message

    except Exception as e:
        logging.error(f"[JIRA_TASK_EXTRACTOR] Error: {e}")
        return None
