"""
Email Summarizer Agent

Analyzes multiple emails to extract and summarize only important information.
"""

import logging
import os
from typing import Any, Dict, List, Optional
from app.cc_agents.memory_retriever.agent import call_memory_retriever
from app.cc_tools.email_tasks import create_email_tasks_mcp_server
from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)


def create_system_prompt(state_prompt: str, bot_name: str) -> str:
    """Create system prompt for Email task extractor

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()
        bot_name: Bot name

    Returns:
        str: System prompt including agent behavior and tool usage principles
    """
    system_prompt = f"""You are {bot_name}, a virtual resident employee who communicates via Slack.

# Basic Instructions
Analyze the received emails to extract **tasks assigned to you** and save them to DB.

{state_prompt}

## Core Action Principles
<important_actions>
1. Analyze the received emails to extract action items assigned to you.
2. If necessary, query the full email body.
3. If there are action items, save them to DB using `mcp__email_tasks__add_email_task`.
4. Summarize and output the processing results.
</important_actions>

## Tool Usage Principles
<how_to_use_tool>
1. If the preview is not enough to make a judgment, you must query the full email body.
2. The assignee's user_id, user_name, channel_id must be found from retrieved_memory.
3. The `text` parameter of `mcp__email_tasks__add_email_task` must start with "{bot_name}, " and be written in the original email's language.
   - Example: "{bot_name}, please review the design document and submit feedback regarding 'Document Review Request' sent by John Smith."
4. If there are multiple tasks in one email, each must be saved **separately**.
5. If user_id, user_name, channel_id cannot all be found, do not save that task.
6. If you need to create files, always create them temporarily in `FILESYSTEM_BASE_DIR/checkers/tmp/` directory, and delete after completion.
</how_to_use_tool>

## Guardrail Policy
<guardrails>
**File System Access Restriction:**
- Never access files or directories outside FILESYSTEM_BASE_DIR
- Reading or modifying system files, home directory, config files, etc. is strictly prohibited
- File operations must be limited to within FILESYSTEM_BASE_DIR
</guardrails>"""

    return system_prompt


async def call_email_task_extractor(
    emails: List[Dict[str, Any]]
) -> Optional[str]:
    """
    Analyzes email batch to extract tasks and save them to DB.

    Args:
        emails: Email list (including from, subject, body, receivedDateTime)

    Returns:
        Optional[str]: Processing result summary (None if no tasks)
    """
    if not emails:
        return None

    # Convert email list to text
    emails_text = ""
    for idx, email in enumerate(emails, 1):
        email_id = email.get("id", "")
        from_info = email.get("from", {}).get("emailAddress", {})
        from_name = from_info.get("name", "Unknown")
        from_address = from_info.get("address", "")
        subject = email.get("subject", "")
        body_preview = email.get("bodyPreview", "")
        received_time = email.get("receivedDateTime", "")
        has_attachments = email.get("hasAttachments", False)

        # Extract recipient info
        to_recipients = email.get("toRecipients", [])
        to_list = [f"{r.get('emailAddress', {}).get('name', '')} <{r.get('emailAddress', {}).get('address', '')}>" for r in to_recipients]
        to_text = ", ".join(to_list) if to_list else "None"

        # Extract CC recipient info
        cc_recipients = email.get("ccRecipients", [])
        cc_list = [f"{r.get('emailAddress', {}).get('name', '')} <{r.get('emailAddress', {}).get('address', '')}>" for r in cc_recipients]
        cc_text = ", ".join(cc_list) if cc_list else "None"

        emails_text += f"""
Email {idx}:
Email ID: {email_id}
Sender: {from_name} <{from_address}>
Recipients: {to_text}
CC: {cc_text}
Subject: {subject}
Received: {received_time}
Attachments: {"Yes" if has_attachments else "No"}
Body Preview:
{body_preview}

---
"""

    # Get settings and bot_name first
    from app.cc_agents.state_prompt import create_state_prompt
    from app.config.settings import get_settings

    settings = get_settings()
    bot_name = settings.BOT_NAME or "Bot"

    email_task_memory_query = f"""Find information about all people related to the senders in the following {len(emails)} emails and compile memory.
Make sure to include **instructions** and information (channel_id, user_id, user_name) about the channel and requesting user.

{emails_text}"""

    # 1. Memory search (for email task extractor)
    retrieved_memory = await call_memory_retriever(
        email_task_memory_query
    )
    logging.info(f"[EMAIL_TASK_EXTRACTOR] Memory retrieved: {retrieved_memory[:100] if retrieved_memory else 'None'}...")

    state_prompt = create_state_prompt()

    # Add memory
    state_prompt += f"\n\n## Related Memory\n<retrieved_memory>\n{retrieved_memory}\n</retrieved_memory>"

    system_prompt = create_system_prompt(state_prompt, bot_name)

    # 2. Call email task extractor
    query = f"""Extract tasks assigned to you ({bot_name}) from the following {len(emails)} emails and save them to DB.

Use the `email-action-extractor` skill to extract action items.

{emails_text}"""

    # Lokka MCP server settings (cached version)
    mcp_servers = {
        "ms365": {
            "command": "npx",
            "args": ["mcp-cache", "npx", "-y", "@batteryho/lokka-cached"],
            "env": {
                "TENANT_ID": settings.MS365_TENANT_ID,
                "CLIENT_ID": settings.MS365_CLIENT_ID,
                "USE_INTERACTIVE": "true"
            }
        },
        "email_tasks": create_email_tasks_mcp_server()
    }

    options = ClaudeAgentOptions(
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_SIMPLE,
        permission_mode="bypassPermissions",
        allowed_tools=["*"],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
            "Write",
            "Edit",
            "NotebookEdit",
        ],
        setting_sources=['project'],
        cwd=os.getcwd(),
        mcp_servers=mcp_servers
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(query)

            result_message = ""
            async for message in client.receive_response():
                if isinstance(message, ResultMessage):
                    result_message = message.result.strip()
                    logging.info(f"[EMAIL_TASK_EXTRACTOR] Result: {result_message[:100]}...")
                    break

            # Return None if no tasks
            if not result_message or ("no task" in result_message.lower() and "found" in result_message.lower()):
                logging.info("[EMAIL_TASK_EXTRACTOR] No tasks extracted")
                return None

            return result_message

    except Exception as e:
        logging.error(f"[EMAIL_TASK_EXTRACTOR] Error: {e}")
        return None
